file:
    - 'tests/functional/api/movies/index.js'
    - 'tests/functional/api/users/index.js'
    - 'tests/functional/api/upcomingMovies/index.js'
require: '@babel/register'
exit: true
timeout: 4000
